"""German A2 grammar aligned with Goethe Start Deutsch 2 (GER A2)."""
from lesson_util import G, L

LESSONS = [
    L(
        'perfekt', 'A2', 'Perfekt', '德文 A2｜現在完成式',
        '口語說過去，多用 Perfekt：助動詞 haben 或 sein 放在第二位，過去分詞放在句尾。',
        'haben 與 sein 的選擇、規則與不規則過去分詞，附例句、中文、朗讀與 PDF。',
        '移動、狀態改變，以及 sein、bleiben、werden，助動詞用 sein。\n大多數其他動詞用 haben。不可分前綴 be-、er-、ver- 的過去分詞不加 ge。',
        [
            G('haben', '規則與不規則過去分詞', [
                ['學習', 'gelernt', '學過'],
                ['工作', 'gearbeitet', '工作過'],
                ['讀', 'gelesen', '讀過'],
                ['說', 'gesprochen', '說過'],
            ], [
                ['Ich habe gestern Deutsch gelernt.', '我昨天學了德文。'],
                ['Hast du schon gegessen?', '你吃過了嗎？'],
                ['Er hat einen Kaffee getrunken.', '他喝了一杯咖啡。'],
                ['Wir haben Freunde besucht.', '我們拜訪了朋友。'],
            ]),
            G('sein', '移動、停留、sein', [
                ['去', 'gegangen', '去過'],
                ['來', 'gekommen', '來過'],
                ['搭', 'gefahren', '搭過'],
                ['停留', 'geblieben', '留過'],
            ], [
                ['Ich bin nach Hause gegangen.', '我回家了。'],
                ['Sie ist mit dem Bus gekommen.', '她搭公車來了。'],
                ['Wir sind nach Berlin gefahren.', '我們去了柏林。'],
                ['Bist du zu Hause geblieben?', '你留在家裡了嗎？'],
            ]),
            G('句中的位置', '助動詞第二位，分詞句尾', [
                ['昨天', 'Gestern habe ich gelesen.', '昨天我讀了書。'],
                ['已經', 'Ich habe schon gegessen.', '我已經吃了。'],
                ['從未', 'Ich bin noch nie in Berlin gewesen.', '我從來沒去過柏林。'],
                ['疑問', 'Hast du das Buch gelesen?', '你讀了那本書嗎？'],
            ], [
                ['Gestern habe ich ein Buch gelesen.', '昨天我讀了一本書。'],
                ['Ich habe die E-Mail schon geschrieben.', '我已經寫了那封電子郵件。'],
                ['Sie ist noch nie in Taiwan gewesen.', '她從來沒來過台灣。'],
                ['Was hast du am Wochenende gemacht?', '你週末做了什麼？'],
            ]),
        ],
    ),
    L(
        'war-hatte', 'A2', 'War und Hatte', '德文 A2｜war 與 hatte',
        'sein 和 haben 說過去時，口語也常用簡單過去：war 和 hatte。其他動詞的簡單過去留到 B1。',
        'war、hatte 的六組人稱，以及和 Perfekt 的分工，附例句、中文、朗讀與 PDF。',
        '敘述昨天做了什麼，一般動詞仍用 Perfekt：Ich habe gelernt。\n是、有、在，常用 war 和 hatte：Ich war müde. Ich hatte Zeit.',
        [
            G('war', 'sein 的過去', [
                ['ich / er', 'war', '當時是'],
                ['du', 'warst', '你當時是'],
                ['wir / sie', 'waren', '當時是'],
                ['ihr', 'wart', '你們當時是'],
            ], [
                ['Ich war gestern müde.', '我昨天很累。'],
                ['Wo warst du?', '你當時在哪裡？'],
                ['Wir waren zu Hause.', '我們當時在家。'],
                ['Der Kurs war interessant.', '那堂課很有趣。'],
            ]),
            G('hatte', 'haben 的過去', [
                ['ich / er', 'hatte', '當時有'],
                ['du', 'hattest', '你當時有'],
                ['wir / sie', 'hatten', '當時有'],
                ['ihr', 'hattet', '你們當時有'],
            ], [
                ['Ich hatte keine Zeit.', '我當時沒有時間。'],
                ['Hattest du Hunger?', '你當時餓嗎？'],
                ['Wir hatten eine Frage.', '我們當時有一個問題。'],
                ['Sie hatte einen Bruder.', '她當時有一個兄弟。'],
            ]),
            G('怎麼選', 'war、hatte 或 Perfekt', [
                ['狀態', 'Ich war krank.', '我當時生病。'],
                ['擁有', 'Ich hatte ein Buch.', '我當時有一本書。'],
                ['做過的事', 'Ich habe geschlafen.', '我睡了。'],
                ['去過', 'Ich bin gegangen.', '我去了。'],
            ], [
                ['Gestern war ich zu Hause.', '昨天我在家。'],
                ['Ich hatte leider keine Zeit.', '我當時可惜沒有時間。'],
                ['Ich habe zehn Stunden geschlafen.', '我睡了十個小時。'],
                ['Danach bin ich spazieren gegangen.', '之後我去散步了。'],
            ]),
        ],
        cols=('人稱', '形式', '中文'),
    ),
    L(
        'trennbar', 'A2', 'Trennbar', '德文 A2｜可分動詞',
        '可分動詞的前綴在現在式裡放到句尾。完成式的 ge 夾在前綴和詞幹中間。',
        'aufstehen、anrufen、einkaufen 的現在式、命令句與 Perfekt，附例句、中文、朗讀與 PDF。',
        '前綴在句尾，中間可以放很多詞：Ich stehe um sieben Uhr auf。\n完成式：aufgestanden、angerufen、eingekauft。mitkommen 用 sein。',
        [
            G('現在式', '前綴放句尾', [
                ['起床', 'ich stehe auf', '我起床'],
                ['打電話', 'er ruft an', '他打電話'],
                ['購物', 'wir kaufen ein', '我們購物'],
                ['一起去', 'kommst du mit?', '你一起去嗎？'],
            ], [
                ['Ich stehe um sieben auf.', '我七點起床。'],
                ['Er ruft seine Mutter an.', '他打電話給他母親。'],
                ['Wir kaufen am Samstag ein.', '我們星期六購物。'],
                ['Kommst du heute mit?', '你今天一起去嗎？'],
            ]),
            G('Perfekt', 'ge 夾在前綴中間', [
                ['起床', 'aufgestanden', '起床了（用 sein）'],
                ['打電話', 'angerufen', '打過電話'],
                ['購物', 'eingekauft', '買過東西'],
                ['一起去', 'mitgekommen', '一起去了（用 sein）'],
            ], [
                ['Ich bin um sieben aufgestanden.', '我七點起了床。'],
                ['Hast du Anna angerufen?', '你打電話給 Anna 了嗎？'],
                ['Wir haben gestern eingekauft.', '我們昨天買了東西。'],
                ['Sie ist mitgekommen.', '她一起去了。'],
            ]),
            G('命令句', '前綴仍在句尾', [
                ['du', 'Steh auf!', '起床！'],
                ['ihr', 'Steht auf!', '你們起床！'],
                ['Sie', 'Stehen Sie auf!', '請您起床！'],
                ['開門', 'Mach die Tür auf!', '把門打開！'],
            ], [
                ['Steh bitte auf!', '請起床！'],
                ['Ruf mich später an!', '晚點打電話給我！'],
                ['Kommen Sie bitte mit!', '請您一起去！'],
                ['Machen Sie das Fenster auf!', '請打開窗戶！'],
            ]),
        ],
    ),
    L(
        'dativ', 'A2', 'Dativ', '德文 A2｜與格',
        '給誰、幫誰、對誰，用與格。複數與格冠詞是 den，名詞通常再加 -n。',
        '與格冠詞、人稱代名詞，以及 helfen、danken、gefallen、gehören，附例句、中文、朗讀與 PDF。',
        '複數與格：den Kindern，den Freunden。名詞若已是 -n 或 -s，就不再加：den Eltern，den Autos。\n人稱：mir、dir、ihm、ihr、uns、euch、ihnen、Ihnen。',
        [
            G('冠詞', '陽性與中性都變成 dem', [
                ['陽性', 'dem Mann / einem Freund', '這個男人／一位朋友'],
                ['陰性', 'der Frau / einer Freundin', '這個女人／一位女性朋友'],
                ['中性', 'dem Kind / einem Kind', '這個孩子'],
                ['複數', 'den Kindern', '這些孩子'],
            ], [
                ['Ich helfe dem Mann.', '我幫助那個男人。'],
                ['Das Buch gehört der Frau.', '這本書是那個女人的。'],
                ['Wir danken einem Freund.', '我們感謝一位朋友。'],
                ['Sie gibt den Kindern Wasser.', '她拿水給孩子們。'],
            ]),
            G('人稱代名詞', '給我、給你、給他', [
                ['我／你', 'mir / dir', '我／你'],
                ['他／她', 'ihm / ihr', '他／她'],
                ['我們／你們', 'uns / euch', '我們／你們'],
                ['他們／您', 'ihnen / Ihnen', '他們／您'],
            ], [
                ['Kannst du mir helfen?', '你能幫我嗎？'],
                ['Ich danke dir.', '我謝謝你。'],
                ['Das Buch gefällt ihm.', '他喜歡這本書。'],
                ['Wie geht es Ihnen?', '您好嗎？'],
            ]),
            G('固定用與格的動詞', '不是直接受詞', [
                ['幫助', 'helfen + 與格', '幫助某人'],
                ['感謝', 'danken + 與格', '感謝某人'],
                ['喜歡', 'gefallen + 與格', '令某人喜歡'],
                ['屬於', 'gehören + 與格', '屬於某人'],
            ], [
                ['Ich helfe meiner Mutter.', '我幫我母親。'],
                ['Wir danken Ihnen.', '我們感謝您。'],
                ['Der Film gefällt mir.', '我喜歡這部電影。'],
                ['Das Auto gehört meinem Bruder.', '這輛車是我兄弟的。'],
            ]),
        ],
    ),
    L(
        'praepositionen', 'A2', 'Präpositionen', '德文 A2｜介系詞與格',
        '有些介系詞永遠跟與格，有些永遠跟受格。雙向介系詞看是位置還是方向。',
        'aus、bei、mit、nach、seit、von、zu，受格介系詞，以及 auf、in 的位置與方向，附例句、中文、朗讀與 PDF。',
        'wo 用與格：Ich bin in der Schule。wohin 用受格：Ich gehe in die Schule。\n常用縮寫：zum、zur、ins、im、am。時間、方式、地點依序放：Ich fahre morgen mit dem Bus nach Berlin。',
        [
            G('永遠與格', 'aus bei mit nach seit von zu', [
                ['從', 'aus Taiwan', '從台灣'],
                ['在某人家', 'bei meinen Eltern', '在我父母家'],
                ['搭乘', 'mit dem Bus', '搭公車'],
                ['自從／去找', 'seit einem Monat / zum Arzt', '一個月以來／去看醫生'],
            ], [
                ['Ich komme aus Taiwan.', '我從台灣來。'],
                ['Sie wohnt bei ihren Eltern.', '她住在父母家。'],
                ['Wir fahren mit dem Zug.', '我們搭火車。'],
                ['Ich lerne seit einem Monat Deutsch.', '我學德文一個月了。'],
            ]),
            G('永遠受格', 'durch für gegen ohne um', [
                ['為了', 'für dich', '為了你'],
                ['穿過', 'durch den Park', '穿過公園'],
                ['沒有', 'ohne dich', '沒有你'],
                ['圍繞', 'um den Tisch', '圍著桌子'],
            ], [
                ['Das Geschenk ist für dich.', '這份禮物是給你的。'],
                ['Wir gehen durch den Park.', '我們穿過公園。'],
                ['Ohne dich gehe ich nicht.', '沒有你我不去。'],
                ['Die Kinder sitzen um den Tisch.', '孩子們圍著桌子坐。'],
            ]),
            G('位置或方向', 'wo 與格，wohin 受格', [
                ['在桌上', 'auf dem Tisch', '在桌上（位置）'],
                ['放到桌上', 'auf den Tisch', '放到桌上（方向）'],
                ['在學校', 'in der Schule', '在學校裡'],
                ['去學校', 'in die Schule', '到學校去'],
            ], [
                ['Das Buch liegt auf dem Tisch.', '書放在桌上。'],
                ['Ich lege das Buch auf den Tisch.', '我把書放到桌上。'],
                ['Wir sind in der Schule.', '我們在學校。'],
                ['Ich gehe in die Schule.', '我去學校。'],
            ]),
        ],
    ),
    L(
        'kasus', 'A2', 'Kasus', '德文 A2｜冠詞與格',
        '冠詞同時看性別、單複數和格。名詞的性別不變；句子角色或介系詞變了，冠詞才變。不要只靠中文翻譯猜 ein、einen、einem、einer。',
        '從性別和格推出 ein、einen、einem、einer：mit、für、定冠詞，以及同一句裡的兩個格，附例句、中文、朗讀與 PDF。',
        '做題先講兩句：這個名詞是什麼性別？誰決定它的格？\n有 mit 就用第三格：陽性、中性 einem，陰性 einer。有 für 就用第四格：陽性 einen，陰性 eine，中性 ein。\n沒有介系詞時，主詞用第一格，sehen 的受詞用第四格，helfen 的受詞用第三格。\n中文的「給」不一定是第三格。geben 的人用第三格，für 後面用第四格。',
        [
            G('三條線', '性別不變，換的是格', [
                ['性別', 'der Mann', '陽性，始終不變'],
                ['單數', 'ein Mann', '一個男人'],
                ['複數', 'die Männer', '複數不用 ein'],
                ['換格', 'einen / einem', '角色變，冠詞才變'],
            ], [
                ['Ein Mann kommt.', '一個男人來了。第一格。'],
                ['Ich sehe einen Mann.', '我看到一個男人。第四格。'],
                ['Ich komme mit einem Mann.', '我跟一個男人一起來。第三格。'],
                ['Eine Frau kommt.', '一個女人來了。Frau 是陰性。'],
            ]),
            G('名詞性別', '字典形式是單數第一格', [
                ['陽性', 'der Mann / die Männer', '男人'],
                ['陰性', 'die Frau / die Frauen', '女人'],
                ['中性', 'das Kind / die Kinder', '小孩，可男可女'],
                ['文字', 'der Text / die Texte', '文字、文本'],
                ['筆', 'der Stift / die Stifte', '筆'],
                ['女孩', 'das Mädchen', '文法中性，因為 -chen'],
            ], [
                ['Das Kind kommt.', '那個小孩來了。das 是冠詞。'],
                ['Das ist ein Kind.', '這是一個小孩。Das 是代名詞。'],
                ['Das Mädchen spielt.', '女孩在玩。文法上是中性。'],
                ['Der Stift ist neu.', '這支筆是新的。'],
            ]),
            G('四個格', '先掌握前三個格', [
                ['第一格', 'wer / was', '主詞'],
                ['第四格', 'wen / was', '直接受詞'],
                ['第三格', 'wem', '某些動詞或介系詞'],
                ['第二格', 'wessen', '誰的，稍後再學'],
            ], [
                ['Ein Mann kommt.', '誰來了？一個男人。'],
                ['Ich sehe einen Mann.', '看到誰？一個男人。'],
                ['Ich helfe einem Mann.', '幫助的對象用第三格。'],
                ['Ich schreibe mit einem Stift.', '用一支筆。不是「給」，mit 要第三格。'],
            ]),
            G('第一格與第四格', '只有陽性單數會變', [
                ['第一格陽性', 'ein Mann', '主詞'],
                ['第一格陰性', 'eine Frau', '主詞'],
                ['第一格中性', 'ein Kind', '主詞'],
                ['第四格陽性', 'einen Mann', 'ein 變成 einen'],
                ['第四格陰性', 'eine Frau', '拼法相同，格不同'],
                ['第四格中性', 'ein Kind', '拼法相同'],
            ], [
                ['Ein Mann kommt.', '一個男人來了。'],
                ['Eine Frau schreibt.', '一個女人在寫字。'],
                ['Ein Kind spielt.', '一個小孩在玩。'],
                ['Ich sehe einen Mann.', '我看到一個男人。'],
                ['Ich sehe eine Frau.', '我看到一個女人。eine 仍是第四格。'],
                ['Ich sehe ein Kind.', '我看到一個小孩。'],
            ]),
            G('第三格', '動詞或介系詞決定', [
                ['幫助', 'einem Mann', 'helfen 接第三格'],
                ['接受的人', 'einem Mann', 'geben 的人'],
                ['給出的東西', 'einen Stift', 'geben 的東西，第四格'],
                ['工具', 'einem Stift', 'mit 接第三格'],
            ], [
                ['Ich helfe einem Mann.', '我幫助一個男人。'],
                ['Ich gebe einem Mann einen Stift.', '我給一個男人一支筆。'],
                ['Ich schreibe mit einem Stift.', '我用一支筆寫字。'],
                ['Ich sehe einen Mann.', 'sehen 的受詞用第四格。'],
            ]),
            G('不定冠詞', '順序是第一、第四、第三格', [
                ['陽性', 'ein / einen / einem', '一、四、三格'],
                ['陰性', 'eine / eine / einer', '第四格拼法不變'],
                ['中性', 'ein / ein / einem', '第三格也用 einem'],
                ['陽性第二格', 'eines Mannes', '名詞加 -es'],
                ['中性第二格', 'eines Kindes', '名詞加 -es'],
                ['沒有複數', 'Kinder', 'eine 不是複數'],
            ], [
                ['Ein Mann kommt.', '第一格：ein Mann。'],
                ['Ich sehe einen Mann.', '第四格：einen Mann。'],
                ['Ich komme mit einem Mann.', '第三格：einem Mann。'],
                ['Das ist das Buch eines Mannes.', '第二格。陽性名詞加 -es。'],
            ]),
            G('für 與 mit', '先看介系詞要求哪一格', [
                ['für 男人', 'für einen Mann', '第四格，不是 einem'],
                ['für 女人', 'für eine Frau', '第四格'],
                ['für 小孩', 'für ein Kind', '第四格'],
                ['mit 男人', 'mit einem Mann', '第三格'],
                ['mit 女人', 'mit einer Frau', '第三格'],
                ['mit 小孩', 'mit einem Kind', '第三格，中性也用 einem'],
            ], [
                ['Das ist für einen Mann.', '這是給一個男人的。für 要第四格。'],
                ['Das ist für ein Kind.', '這是給一個小孩的。'],
                ['Ich komme mit einem Kind.', '我跟一個小孩一起來。'],
                ['Ich komme mit einer Frau.', '我跟一個女人一起來。'],
                ['Ich gebe einem Mann einen Stift.', '這裡的人用第三格，因為是 geben。'],
            ]),
            G('一句兩個格', '定冠詞和不定冠詞分開看', [
                ['誰在寫', 'Alex', '第一格主詞'],
                ['動詞', 'schreibt', '第三人稱單數'],
                ['寫什麼', 'den Text', '第四格，定冠詞'],
                ['用什麼', 'einem Stift', '第三格，不定冠詞'],
            ], [
                ['Alex schreibt den Text mit einem Stift.', 'Alex 用一支筆寫那段文字。'],
                ['Ich schreibe den Text mit einem Stift.', '我用一支筆寫那段文字。den 不變。'],
                ['Was schreibt Alex?', 'Alex 寫什麼？答案是 den Text。'],
                ['Womit schreibt Alex den Text?', '用什麼寫？答案是 mit einem Stift。'],
            ]),
            G('定冠詞', 'der 不一定代表陽性', [
                ['第一格', 'der Mann / ein Mann', '那個／一個'],
                ['第四格', 'den Mann / einen Mann', '陽性單數才變'],
                ['第三格', 'dem Mann / einem Mann', '陽性第三格'],
                ['陰性第三格', 'mit der Frau', '這個 der 是陰性'],
                ['中性第三格', 'mit dem Kind', 'dem 也用於中性'],
                ['複數第三格', 'mit den Kindern', '複數第三格是 den'],
            ], [
                ['Ich sehe den Mann.', '我看到那個男人。'],
                ['Ich sehe einen Mann.', '我看到一個男人。'],
                ['Ich komme mit dem Mann.', '我跟那個男人一起來。'],
                ['Ich komme mit der Frau.', '我跟那個女人來。der 是陰性第三格。'],
            ]),
            G('同一名詞', '句型換了，性別不變', [
                ['男人', 'ein / einen / einem', '來了、看到、一起'],
                ['女人', 'eine / eine / einer', '來了、看到、一起'],
                ['小孩', 'ein / ein / einem', '來了、看到、一起'],
                ['mit 與 für', 'einem / einen Mann', '第三格／第四格'],
                ['女人對照', 'einer / eine Frau', 'mit 與 für'],
                ['小孩對照', 'einem / ein Kind', 'mit 與 für'],
            ], [
                ['Eine Frau kommt.', '一個女人來了。第一格。'],
                ['Ich sehe eine Frau.', '我看到一個女人。第四格。'],
                ['Ich komme mit einer Frau.', '我跟一個女人一起來。第三格。'],
                ['Ein Kind kommt.', '一個小孩來了。'],
                ['Ich sehe ein Kind.', '我看到一個小孩。'],
                ['Ich komme mit einem Kind.', '我跟一個小孩一起來。'],
            ]),
            G('動詞變化', '動詞看人稱，冠詞看格', [
                ['ich', 'komme / schreibe', '我來／我寫'],
                ['du', 'kommst / schreibst', '你來／你寫'],
                ['er / sie', 'kommt / schreibt', '他來／他寫'],
                ['wir', 'kommen / schreiben', '我們來／我們寫'],
                ['ihr', 'kommt / schreibt', '你們來／你們寫'],
                ['sie / Sie', 'kommen / schreiben', '他們來／您寫'],
            ], [
                ['Ich schreibe den Text.', '我寫那段文字。'],
                ['Alex schreibt den Text.', 'Alex 寫那段文字。'],
                ['Wir schreiben den Text.', '我們寫那段文字。受詞仍是 den Text。'],
                ['Ich komme mit einem Mann.', '我來。冠詞仍看格，不看人稱。'],
            ]),
            G('動詞第二位', '第二位是成分，不是單字', [
                ['主詞起頭', 'Ich komme heute.', '動詞在第二位'],
                ['時間起頭', 'Heute komme ich.', '主詞退到動詞後面'],
                ['工具起頭', 'Mit einem Stift schreibt er.', '三個字仍算第一位'],
                ['格不變', 'mit einem Stift', '搬到句首，仍是第三格'],
            ], [
                ['Ich komme mit einem Mann.', '我跟一個男人一起來。'],
                ['Heute komme ich mit einem Mann.', '今天我跟一個男人一起來。'],
                ['Alex schreibt den Text mit einem Stift.', '工具片語放在後面。'],
                ['Mit einem Stift schreibt Alex den Text.', '工具片語放在句首，格不變。'],
            ]),
            G('固定第三格', '格是介系詞的一部分', [
                ['跟、用', 'mit einem Stift', '第三格'],
                ['從裡面', 'aus dem Haus', '第三格'],
                ['在某人家', 'bei einer Freundin', '第三格'],
                ['在……之後', 'nach dem Kurs', '第三格'],
                ['自從', 'seit einem Jahr', '第三格'],
                ['來自', 'von einem Freund', '第三格'],
                ['去找', 'zu einem Arzt', '第三格'],
            ], [
                ['Ich schreibe mit einem Stift.', '我用一支筆寫字。'],
                ['Sie kommt aus dem Haus.', '她從屋子裡出來。'],
                ['Sie wohnt bei einer Freundin.', '她住在一位女性朋友那裡。'],
                ['Ich gehe zu einem Arzt.', '我去一位醫師那裡。'],
            ]),
            G('固定第四格', 'für、ohne、durch、gegen、um', [
                ['為了', 'für einen Mann', '第四格'],
                ['沒有', 'ohne einen Stift', '第四格'],
                ['穿過', 'durch den Park', '第四格'],
                ['朝向', 'gegen die Wand', '第四格'],
                ['圍繞', 'um den Tisch', '第四格'],
            ], [
                ['Das ist für einen Mann.', '這是給一個男人的。'],
                ['Er kommt ohne einen Stift.', '他沒帶筆來。'],
                ['Wir gehen durch den Park.', '我們穿過公園。'],
                ['Die Kinder sitzen um den Tisch.', '孩子們圍著桌子坐。'],
            ]),
            G('雙向介系詞', '位置用第三格，目的地用第四格', [
                ['在房間', 'im Zimmer', '第三格，位置'],
                ['進房間', 'ins Zimmer', '第四格，目的地'],
                ['在公園跑', 'im Park', '有移動，仍是位置'],
                ['跑進公園', 'in den Park', '目的地才用第四格'],
                ['不這樣判斷', 'mit / für', '這兩個的格是固定的'],
            ], [
                ['Ich bin im Zimmer.', '我在房間裡。'],
                ['Ich gehe ins Zimmer.', '我走進房間。'],
                ['Ich laufe im Park.', '我在公園裡跑步。'],
                ['Ich laufe in den Park.', '我跑進公園。'],
            ]),
            G('名詞詞尾', '第三格複數常再加 -n', [
                ['小孩', 'mit den Kindern', 'Kinder 加 -n'],
                ['男人', 'mit den Männern', 'Männer 加 -n'],
                ['女人', 'mit den Frauen', '已經是 -n，不再加'],
                ['汽車', 'mit den Autos', '-s 複數不加 -n'],
                ['學生', 'einem Studenten', '弱變化，單數也加 -en'],
                ['不加', 'mit einem Mann', 'Mann、Text、Stift 不是這一類'],
            ], [
                ['Ich komme mit den Kindern.', '我跟那些小孩一起來。'],
                ['Ich komme mit den Frauen.', '我跟那些女人一起來。'],
                ['Ich sehe einen Studenten.', '我看到一個學生。'],
                ['Ich spreche mit einem Studenten.', '我和一個學生說話。'],
            ]),
            G('mein 與 kein', '詞尾跟著 ein 走', [
                ['我的筆', 'mit meinem Stift', '陽性第三格'],
                ['沒有筆', 'mit keinem Stift', 'kein 像 ein'],
                ['我的女性朋友', 'mit meiner Freundin', '陰性第三格'],
                ['我的父親', 'für meinen Vater', '陽性第四格'],
                ['我的母親', 'für meine Mutter', '陰性第四格'],
                ['我的小孩', 'für mein Kind', '中性第四格'],
            ], [
                ['Ich schreibe mit meinem Stift.', '我用我的筆寫字。'],
                ['Ich komme mit meiner Freundin.', '我跟我的女性朋友一起來。'],
                ['Das ist für meinen Vater.', '這是給我爸爸的。'],
                ['Das ist für mein Kind.', '這是給我的孩子的。'],
            ]),
            G('形容詞', '先把冠詞的格判斷穩', [
                ['第一格陽性', 'ein guter Stift', '形容詞 -er'],
                ['第一格陰性', 'eine gute Freundin', '形容詞 -e'],
                ['第一格中性', 'ein kleines Kind', '形容詞 -es'],
                ['第四格', 'für einen guten Freund', '形容詞 -en'],
                ['第三格陽性', 'mit einem guten Stift', '形容詞 -en'],
                ['第三格中性', 'mit einem kleinen Kind', '形容詞 -en'],
                ['述語', 'Der Stift ist gut.', '不加這種詞尾'],
            ], [
                ['Das ist ein guter Stift.', '這是一支好筆。'],
                ['Das ist für einen guten Freund.', '這是給一位好朋友的。'],
                ['Ich schreibe mit einem guten Stift.', '我用一支好筆寫字。'],
                ['Das Kind ist klein.', '這個孩子很小。klein 不加詞尾。'],
            ]),
            G('自己推導', '先講性別，再講誰決定格', [
                ['跟一個女人', 'einer Frau', '陰性，mit 第三格'],
                ['給一個小孩', 'für ein Kind', '中性，für 第四格'],
                ['看到一個男人', 'einen Mann', '陽性，sehen 第四格'],
                ['用一支筆', 'einem Stift', '陽性，mit 第三格'],
                ['一個小孩來了', 'Ein Kind', '中性主詞，第一格'],
                ['看到一個女人', 'eine Frau', '陰性，第四格不變'],
                ['給一個男人', 'für einen Mann', '陽性，für 第四格'],
                ['跟一個小孩', 'einem Kind', '中性，mit 第三格'],
            ], [
                ['Ich komme mit einer Frau.', '我跟一個女人一起來。'],
                ['Das ist für ein Kind.', '這是給一個小孩的。'],
                ['Ich sehe einen Mann.', '我看到一個男人。'],
                ['Ein Kind kommt.', '一個小孩來了。句首要大寫。'],
            ]),
        ],
    ),
    L(
        'modalverben', 'A2', 'Modalverben', '德文 A2｜情態動詞',
        'müssen 是必須，dürfen 是被允許，sollen 是該做，wollen 是想要。真正的動詞仍以原形放在句尾。',
        'müssen、dürfen、wollen、sollen 的變位，以及不必和禁止的差別，附例句、中文、朗讀與 PDF。',
        'nicht dürfen 是禁止。nicht müssen 是不必。\nkönnen 和 möchten 已在 A1。人稱 man 常和這些動詞一起用：Man darf hier nicht rauchen。',
        [
            G('müssen', '必須', [
                ['ich / er', 'muss', '必須'],
                ['du', 'musst', '你必須'],
                ['wir / sie', 'müssen', '必須'],
                ['ihr', 'müsst', '你們必須'],
            ], [
                ['Ich muss heute arbeiten.', '我今天必須工作。'],
                ['Musst du schon gehen?', '你必須走了嗎？'],
                ['Wir müssen pünktlich sein.', '我們必須準時。'],
                ['Du musst nicht kommen.', '你不必來。'],
            ]),
            G('dürfen', '被允許', [
                ['ich / er', 'darf', '可以'],
                ['du', 'darfst', '你可以'],
                ['wir / sie', 'dürfen', '可以'],
                ['ihr', 'dürft', '你們可以'],
            ], [
                ['Darf ich das Fenster öffnen?', '我可以打開窗戶嗎？'],
                ['Hier darf man nicht rauchen.', '這裡禁止抽菸。'],
                ['Ihr dürft jetzt gehen.', '你們現在可以走了。'],
                ['Kinder dürfen den Wein nicht trinken.', '孩子不可以喝葡萄酒。'],
            ]),
            G('wollen 與 sollen', '想要，以及該做', [
                ['我要', 'ich will', '我想要'],
                ['你要', 'du willst', '你想要'],
                ['我應該', 'ich soll', '我應該'],
                ['您應該', 'Sie sollen', '您應該'],
            ], [
                ['Was willst du trinken?', '你想喝什麼？'],
                ['Sie will Ärztin werden.', '她想當醫生。'],
                ['Wir sollen den Text lesen.', '我們應該讀這篇課文。'],
                ['Soll ich das Fenster zumachen?', '要不要我把窗戶關上？'],
            ]),
        ],
        cols=('人稱', '形式', '中文'),
    ),
    L(
        'komparativ', 'A2', 'Komparativ', '德文 A2｜比較級與最高級',
        '比較級加 -er，最高級用 am ...-sten。一樣用 so ... wie，不一樣用 als。',
        '規則變化、變音、gut 和 gern 的不規則，附例句、中文、朗讀與 PDF。',
        '一樣：so groß wie。不一樣：größer als。\ngut 的比較級是 besser，最高級是 am besten。gern 是 lieber、am liebsten。viel 是 mehr、am meisten。',
        [
            G('規則', '-er 與 am ...-sten', [
                ['小', 'klein / kleiner / am kleinsten', '小／較小／最小'],
                ['快', 'schnell / schneller / am schnellsten', '快／較快／最快'],
                ['有趣', 'interessant / interessanter', '有趣／較有趣'],
                ['最高級', 'am interessantesten', '最有趣'],
            ], [
                ['Dieses Zimmer ist kleiner.', '這間房間比較小。'],
                ['Der Bus ist schneller als das Fahrrad.', '公車比腳踏車快。'],
                ['Das ist am interessantesten.', '那是最有趣的。'],
                ['Der Film ist interessanter als das Buch.', '電影比書有趣。'],
            ]),
            G('變音與不規則', '單音節常見變音', [
                ['大', 'groß / größer / am größten', '大／較大／最大'],
                ['老', 'alt / älter / am ältesten', '年長／較年長／最年長'],
                ['好', 'gut / besser / am besten', '好／較好／最好'],
                ['喜歡', 'gern / lieber / am liebsten', '喜歡／更喜歡／最喜歡'],
            ], [
                ['Taipei ist größer als Tainan.', '台北比台南大。'],
                ['Mein Bruder ist älter als ich.', '我的兄弟比我年長。'],
                ['Dieses Buch ist besser.', '這本書比較好。'],
                ['Am liebsten trinke ich Tee.', '我最喜歡喝茶。'],
            ]),
            G('一樣或不一樣', 'so ... wie 與 als', [
                ['一樣大', 'so groß wie', '和……一樣大'],
                ['不一樣', 'nicht so schwer wie', '沒有……那麼難'],
                ['比', 'größer als', '比……大'],
                ['更多', 'mehr als', '比……多'],
            ], [
                ['Sie spricht so gut wie du.', '她說得和你一樣好。'],
                ['Deutsch ist nicht so schwer wie Chinesisch.', '德文沒有中文那麼難。'],
                ['Er ist größer als sein Bruder.', '他比他的兄弟高。'],
                ['Ich habe mehr Zeit als gestern.', '我的時間比昨天多。'],
            ]),
        ],
    ),
    L(
        'adjektiv', 'A2', 'Adjektiv', '德文 A2｜形容詞詞尾',
        '形容詞放在 sein 後面、單獨描述時不加詞尾。放在冠詞和名詞中間才加詞尾。',
        '述語不加詞尾、定冠詞後的詞尾、ein 後面的詞尾，附例句、中文、朗讀與 PDF。',
        '先看冠詞，再看名詞的性別和格。\n陽性受格最容易錯：einen heißen Kaffee，den kleinen Tisch。',
        [
            G('述語', 'sein 後面不加詞尾', [
                ['熱', 'Der Kaffee ist heiß.', '咖啡是熱的。'],
                ['冷', 'Das Wasser ist kalt.', '水是冷的。'],
                ['好', 'Die Idee ist gut.', '這個主意很好。'],
                ['新', 'Die Bücher sind neu.', '這些書是新的。'],
            ], [
                ['Der Kaffee ist heiß.', '咖啡是熱的。'],
                ['Die Suppe ist warm.', '湯是溫的。'],
                ['Das Kind ist müde.', '孩子累了。'],
                ['Die Fragen sind schwer.', '這些問題很難。'],
            ]),
            G('定冠詞後面', 'der heiße Kaffee', [
                ['主格陽性', 'der heiße Kaffee', '熱咖啡'],
                ['受格陽性', 'den heißen Kaffee', '熱咖啡（受格）'],
                ['陰性', 'die gute Idee', '好主意'],
                ['複數', 'die neuen Bücher', '新書'],
            ], [
                ['Der heiße Kaffee steht auf dem Tisch.', '熱咖啡放在桌上。'],
                ['Ich trinke den heißen Kaffee.', '我喝這杯熱咖啡。'],
                ['Die gute Idee gefällt mir.', '我喜歡這個好主意。'],
                ['Die neuen Bücher sind teuer.', '這些新書很貴。'],
            ]),
            G('ein 後面', 'ein heißer Kaffee', [
                ['主格陽性', 'ein heißer Kaffee', '一杯熱咖啡'],
                ['受格陽性', 'einen heißen Kaffee', '一杯熱咖啡（受格）'],
                ['陰性', 'eine gute Idee', '一個好主意'],
                ['中性', 'ein kaltes Getränk', '一杯冷飲'],
            ], [
                ['Das ist ein heißer Kaffee.', '那是一杯熱咖啡。'],
                ['Ich möchte einen heißen Kaffee.', '我想要一杯熱咖啡。'],
                ['Sie hat eine gute Idee.', '她有一個好主意。'],
                ['Er bestellt ein kaltes Getränk.', '他點一杯冷飲。'],
            ]),
        ],
    ),
    L(
        'reflexiv', 'A2', 'Reflexiv', '德文 A2｜反身動詞',
        '動作回到主詞自己身上時，用反身代名詞。第三人稱和尊稱用 sich，其餘用人稱受格或與格。',
        'mich、dich、sich，身體部位的與格，以及 sich freuen auf 和 über，附例句、中文、朗讀與 PDF。',
        '受格反身：mich、dich、sich、uns、euch、sich。\n身體部位用與格反身，再加受格名詞：Ich wasche mir die Hände。',
        [
            G('受格反身', '洗自己、穿上、見面', [
                ['我', 'ich wasche mich', '我洗澡'],
                ['你', 'du wäschst dich', '你洗澡'],
                ['他', 'er zieht sich an', '他穿衣服'],
                ['我們', 'wir treffen uns', '我們見面'],
            ], [
                ['Ich wasche mich jeden Morgen.', '我每天早上洗澡。'],
                ['Wäschst du dich mit kaltem Wasser?', '你用冷水洗澡嗎？'],
                ['Er zieht sich schnell an.', '他很快穿上衣服。'],
                ['Wir treffen uns um acht.', '我們八點見面。'],
            ]),
            G('與格反身', '洗自己的某個部位', [
                ['手', 'ich wasche mir die Hände', '我洗手'],
                ['牙', 'du putzt dir die Zähne', '你刷牙'],
                ['頭髮', 'er kämmt sich die Haare', '他梳頭髮'],
                ['完成式', 'ich habe mir die Hände gewaschen', '我洗了手'],
            ], [
                ['Ich wasche mir die Hände.', '我洗手。'],
                ['Putzt du dir die Zähne?', '你刷牙了嗎？'],
                ['Sie kämmt sich die Haare.', '她梳頭髮。'],
                ['Er hat sich die Jacke angezogen.', '他穿上了外套。'],
            ]),
            G('固定搭配', '介系詞不能換', [
                ['期待', 'sich freuen auf + 受格', '期待尚未發生的事'],
                ['感到高興', 'sich freuen über + 受格', '為已經發生的事高興'],
                ['對……有興趣', 'sich interessieren für', '對某事有興趣'],
                ['坐下', 'ich setze mich', '我坐下'],
            ], [
                ['Ich freue mich auf den Kurs.', '我期待這堂課。'],
                ['Sie freut sich über das Geschenk.', '她為這份禮物感到高興。'],
                ['Er interessiert sich für Musik.', '他對音樂有興趣。'],
                ['Setz dich bitte!', '請坐下！'],
            ]),
        ],
    ),
    L(
        'nebensatz', 'A2', 'Nebensatz', '德文 A2｜從句',
        'weil、dass、wenn、ob 開頭的從句，動詞放到該從句的句尾。denn 不是從句，動詞仍在第二位。',
        'weil、dass、wenn、ob 與 denn 的動詞位置，附例句、中文、朗讀與 PDF。',
        'weil 把動詞送到句尾。denn 後面仍是正常主句：動詞第二位。\n從句前要加逗號。ob 用來轉述是非問句，dass 用來轉述一件事。',
        [
            G('weil 與 denn', '原因的兩種動詞位置', [
                ['因為（從句）', 'weil ich krank bin', '因為我生病'],
                ['因為（主句）', 'denn ich bin krank', '因為我生病'],
                ['所以留下', 'Ich bleibe zu Hause', '我留在家裡'],
                ['逗號', 'zu Hause, weil ...', '從句前要逗號'],
            ], [
                ['Ich bleibe zu Hause, weil ich krank bin.', '我留在家裡，因為我生病。'],
                ['Ich bleibe zu Hause, denn ich bin krank.', '我留在家裡，因為我生病。'],
                ['Sie lernt Deutsch, weil sie die Sprache braucht.', '她學德文，因為她需要這個語言。'],
                ['Er kommt nicht, denn er hat keine Zeit.', '他不來，因為他沒有時間。'],
            ]),
            G('dass 與 ob', '一件事，或是不是', [
                ['一件事', 'dass er kommt', '他會來'],
                ['不知道是不是', 'ob sie kommt', '她來不來'],
                ['我想', 'Ich denke, dass ...', '我認為……'],
                ['我不知道', 'Ich weiß nicht, ob ...', '我不知道是否……'],
            ], [
                ['Ich denke, dass er morgen kommt.', '我認為他明天會來。'],
                ['Sie sagt, dass sie müde ist.', '她說她累了。'],
                ['Ich weiß nicht, ob sie Zeit hat.', '我不知道她有沒有時間。'],
                ['Weißt du, ob der Kurs heute ist?', '你知道今天有沒有課嗎？'],
            ]),
            G('wenn', '如果、每當', [
                ['如果有時間', 'wenn ich Zeit habe', '如果我有時間'],
                ['從句在前', 'Wenn ich Zeit habe, koche ich.', '如果我有時間，我就煮飯。'],
                ['每當', 'wenn es regnet', '每當下雨'],
                ['動詞', '在從句句尾', 'habe、regnet'],
            ], [
                ['Wenn ich Zeit habe, koche ich.', '如果我有時間，我就煮飯。'],
                ['Ich bleibe hier, wenn es regnet.', '如果下雨，我就留在這裡。'],
                ['Wenn du willst, kommen wir mit.', '如果你願意，我們就一起去。'],
                ['Ruf mich an, wenn du ankommst.', '你到了就打電話給我。'],
            ]),
        ],
    ),
]
