"""Shared self-introduction lines for per-language pages and comparison tables."""

# (zh, en, de, fr, ja_kanji, ja_kana, ja_roma)
# Name follows the site’s existing Hao-Cheng examples.
LINES = [
    (
        '我叫 Hao-Cheng。',
        'My name is Hao-Cheng.',
        'Ich heiße Hao-Cheng.',
        'Je m’appelle Hao-Cheng.',
        '私はハオチェンと言います。',
        'わたし は ハオチェン と いいます。',
        'Watashi wa haochen to iimasu.',
    ),
    (
        '我今年三十三歲。',
        'I am 33 years old.',
        'Ich bin 33 Jahre alt.',
        'J’ai 33 ans.',
        '私は三十三歳です。',
        'わたし は さんじゅうさんさい です。',
        'Watashi wa sanjuusansai desu.',
    ),
    (
        '我來自台灣。',
        'I am from Taiwan.',
        'Ich komme aus Taiwan.',
        'Je viens de Taïwan.',
        '台湾出身です。',
        'たいわん しゅっしん です。',
        'Taiwan shusshin desu.',
    ),
    (
        '我目前住在桃園，在台北工作。',
        'I currently live in Taoyuan and work in Taipei.',
        'Ich wohne derzeit in Taoyuan und arbeite in Taipei.',
        'J’habite actuellement à Taoyuan et je travaille à Taipei.',
        '今は桃園に住んでいて、台北で働いています。',
        'いま は とうえん に すんでいて、 たいぺい で はたらいて います。',
        'Ima wa touen ni sundeite, taipei de hataraite imasu.',
    ),
    (
        '我的母語是中文。',
        'My native language is Chinese.',
        'Meine Muttersprache ist Chinesisch.',
        'Ma langue maternelle est le chinois.',
        '母語は中国語です。',
        'ぼご は ちゅうごくご です。',
        'Bogo wa chuugokugo desu.',
    ),
    (
        '我會說中文、英文、德文、法文、日文。',
        'I speak Chinese, English, German, French, and Japanese.',
        'Ich spreche Chinesisch, Englisch, Deutsch, Französisch und Japanisch.',
        'Je parle chinois, anglais, allemand, français et japonais.',
        '中国語と英語とドイツ語とフランス語と日本語が話せます。',
        'ちゅうごくご と えいご と ドイツご と フランスご と にほんご が はなせます。',
        'Chuugokugo to eigo to doitsugo to furansugo to nihongo ga hanasemasu.',
    ),
    (
        '我喜歡讀書、慢跑和旅遊。',
        'I like reading, jogging, and traveling.',
        'Ich lese gerne, jogge gerne und reise gerne.',
        'J’aime lire, faire du jogging et voyager.',
        '読書とジョギングと旅行が好きです。',
        'どくしょ と ジョギング と りょこう が すき です。',
        'Dokusho to jogingu to ryokou ga suki desu.',
    ),
    (
        '我喜歡看古老的教堂、寺廟、戰場紀念碑和博物館。',
        'I enjoy visiting old churches, temples, battlefield memorials, and museums.',
        'Ich besuche gerne alte Kirchen, Tempel, Schlachtfeld-Denkmäler und Museen.',
        'J’aime visiter les vieilles églises, les temples, les monuments de champs de bataille et les musées.',
        '古い教会やお寺、戦場の記念碑や博物館を見るのが好きです。',
        'ふるい きょうかい や おてら、 せんじょう の きねんひ や はくぶつかん を みる の が すき です。',
        'Furui kyoukai ya otera, senjou no kinenhi ya hakubutsukan o miru no ga suki desu.',
    ),
    (
        '我喜歡台灣的老建築。',
        'I like Taiwan’s historic architecture.',
        'Ich mag Taiwans alte Architektur.',
        'J’aime l’architecture ancienne de Taïwan.',
        '台湾の古い建物が好きです。',
        'たいわん の ふるい たてもの が すき です。',
        'Taiwan no furui tatemono ga suki desu.',
    ),
    (
        '我很常喝咖啡和茶。',
        'I often drink coffee and tea.',
        'Ich trinke oft Kaffee und Tee.',
        'Je bois souvent du café et du thé.',
        'よくコーヒーやお茶を飲みます。',
        'よく コーヒー や おちゃ を のみます。',
        'Yoku koohii ya ocha o nomimasu.',
    ),
    (
        '我喜歡東亞的日本與中國文化。',
        'I like East Asian cultures—Japanese and Chinese.',
        'Ich mag die ostasiatische Kultur Japans und Chinas.',
        'J’aime les cultures est-asiatiques du Japon et de la Chine.',
        '東アジアの日本と中国の文化が好きです。',
        'ひがしアジア の にほん と ちゅうごく の ぶんか が すき です。',
        'Higashi ajia no nihon to chuugoku no bunka ga suki desu.',
    ),
    (
        '我喜歡歐洲的法國與德國文化。',
        'I like European cultures—French and German.',
        'Ich mag die europäische Kultur Frankreichs und Deutschlands.',
        'J’aime les cultures européennes de la France et de l’Allemagne.',
        'ヨーロッパのフランスとドイツの文化が好きです。',
        'ヨーロッパ の フランス と ドイツ の ぶんか が すき です。',
        'Yooroppa no furansu to doitsu no bunka ga suki desu.',
    ),
]

SECTIONS = [
    ('自我介紹', LINES),
]
